# Generated by Django 6.0 on 2026-01-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
