# Generated by Django 6.0 on 2026-01-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_comment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_notice', '-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
